server:
  port: 8083

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: "{cipher}9f3cacd07937afe55b0971b1011c464a414e0763eab207c93f75290608c20aa1"
    password: "{cipher}437b7ee644e61a99d7b95a1ffdde6b5c8139b948ba5502f4a82c8b8c06c6bf71"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      probes:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

logging:
  level:
    org.springframework.security: TRACE

jwt:
  secret:
    key: "{cipher}c6a4b36d9f669b4d35a44bd99a6262385c17b2b0d4f0e5c120e0a65b10735294d6d8dfa9b29c8ddf359560f74e788ead51ac1348f7c1c21a5add64a165e83f1c"
  accessToken:
    expiration: 900000
  refreshToken:
    expiration: 604800000
